apiVersion: batch/v1
kind: Job
metadata:
  name: spark-demos
spec:
  template:
    metadata:
      name: spark-demos
    spec:
      containers:
      - name: spark-demos
        image: navicore/spark-demos
        env:
          - name: DRIVER_VAR
            value: "Amy"
          - name: DRIVER_PASSENGER_VAR
            value: "Joe"
        args: ["--deploy-mode", "client", "--master", "spark://ed162-spark-master:7077", "--conf", "spark.executorEnv.EXECUTOR_VAR=Artie", "--class", "onextent.sparkdemos.HelloEnv", "/app/target/scala-2.11/SparkDemo-assembly-1.0.jar"]
      restartPolicy: OnFailure

